package br.edu.ocdrf.discovery.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.2-b05-RC1 Generated
 * source version: 2.1.2
 *
 */
@XmlRootElement(name = "DiscoveryException", namespace = "http://discovery.cdrf.edu.br")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscoveryException", namespace = "http://discovery.cdrf.edu.br")
public class DiscoveryExceptionBean {

    private String message;

    /**
     *
     * @return returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     *
     * @param message the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

}
